name: PR Preview
on: pull_request

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up token
        id: token
        # This is a base64-encoded OAuth token for the "trust-git-bot" GitHub account, which has no secure access.
        run: echo "::set-output name=GH_TOKEN::`echo 'Z2hwX3FpcFc2WFJtVTdpOXo1OGZhUUVYWXlBTXZxTHVjTzIxUWdhRA==' | base64 -d`"

      - uses: actions/checkout@v3

      - name: Install trunk
        run: |
          curl -sL https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz -o trunk-x86_64-unknown-linux-gnu.tar.gz
          tar xzf trunk-x86_64-unknown-linux-gnu.tar.gz
          sudo install trunk /usr/bin/trunk
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install NPM dependencies
        run: npm install

      - name: Set build timestamp
        run: echo "BUILD_TIMESTAMP=$(date --rfc-3339=seconds --utc)" >> $GITHUB_ENV
      - name: Build page
        env:
          BUILD_COMMIT: ${{ github.sha }}
        run: trunk build --public-url /

      - name: Generate Surge URL
        uses: actions/github-script@v3
        id: surge-url
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number } } = context;
            return `patternfly-yew-quickstarts-pr-${issue_number}-preview.surge.sh`;
          result-encoding: string
      - name: Install Surge
        run: npm install -g surge
      - name: Deploy to Surge
        run: surge ./dist/ "${{steps.surge-url.outputs.result}}" --token 62bd7a07b9bf812ff8d3ea91ccd2dc2f
      - name: Post URL as PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "🚀 Deployed Preview: http://${{steps.surge-url.outputs.result}} ✨"
          repo-token: ${{ steps.token.outputs.GH_TOKEN }}
